### PR TITLE
Branch fix bug

### LINKED ISSUE #166: [Bug] Fix bug where module lesson clashing not detected if event is more than a week long
## Bug Description

The event-module clash will not be detected if the event is longer than a week e.g (Event runs from Monday to following Tuesday) and the clash warning message will not be printed.

## Possible Fix

1. Iterate through each date the event runs through and check the calendar based on the day of that each date.
2. If event runs longer than a week, check through the entire calendar once.

### PR DESCRIPTION
**Pull request by PoobalanAatmikaLakshmi**
closes #166

### CODE REVIEW

File: src/main/java/seedu/apollo/command/task/AddCommand.java [hunk 1]
```diff
@@ -251,22 +251,17 @@ private void warnEventModuleClash(Ui ui, Calendar calendar, Event event) {
...
-            if (isClashingEventModule(calendar.get(index), eventStart, eventEnd, currentDayString)) {
+            if (isClashingEventModule(calendar.get(currentDayIndex), eventStart, eventEnd, currentDayString)) {
                 ui.printClashingEventModuleMessage();
                 return;
             }
-            index = (index + 1) % 7;
+
             currentDay = currentDay.plusDays(1);
-        } while (index != endIndex);
+        } while (!currentDay.isAfter(eventEnd));
```
Comment (honglinshang) [inline src/main/java/seedu/apollo/command/task/AddCommand.java:264]: Good execution of stopping do while loop!

**Review by honglinshang — COMMENTED** [review]
Looks good to me!
