### PR TITLE
Fixed bug for event and lessons clash 

### LINKED ISSUE #165: [Bug] Constrain clashing event and lessons warning to only dates during the semester.
## Bug Description

Currently, Apollo assumes your lessons run throughout the year, with no regard for Academic Semester dates. Will show warning for events and lessons even for events which are not during the semester.

Example of bug:

Screenshot 2023-03-31 at 12 38 45 PM

## Possible Fix

Configure Apollo to be able to detect if a date is outside the current academic semester and schedule calendar accordingly.

By:

1. Ignoring modules after semester end date.

### PR DESCRIPTION
**Pull request by PoobalanAatmikaLakshmi**
closes #165

### CODE REVIEW

File: src/main/java/seedu/apollo/command/task/AddCommand.java [hunk 1]
```diff
@@ -279,13 +279,32 @@ private boolean isClashingEventModule(ArrayList<CalendarModule> calendarModule,
...
+        LocalDateTime startSemesterTwo = LocalDateTime.of(2023, 1, 9, 0, 0);
+        LocalDateTime endSemesterTwo= LocalDateTime.of(2023,5,7,0,0);
+        LocalDateTime startSemesterOne = LocalDateTime.of(2023,8,14,0,0);
+        LocalDateTime endSemesterOne = LocalDateTime.of(2023,11,10,0,0);
+        return (!startSemesterTwo.isAfter(eventEnd) && !endSemesterTwo.isBefore(eventStart))
+                || (!startSemesterOne.isAfter(eventEnd) && !endSemesterOne.isBefore(eventStart));
+    }
+
+
+
```
Comment (irving11119) [inline src/main/java/seedu/apollo/command/task/AddCommand.java:307]: Hmmm looks fine!

**Review by irving11119 — APPROVED** [review]
