### PR TITLE
Fix issues with corrupted save file

### LINKED ISSUE #194: [PE-D][Tester D] Crash
Program crashes when save file is modified ('T' removed)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tanyizhe/ped#10

### LINKED ISSUE #195: [PE-D][Tester D] Corrupted file causing immediate crash
program crashes when save file is corrupted.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: tanyizhe/ped#11

### PR DESCRIPTION
**Pull request by honglinshang**
Fix #195 
Fix #194

### CODE REVIEW

File: src/main/java/seedu/apollo/storage/Storage.java [hunk 1]
```diff
@@ -314,9 +315,16 @@ private static void addLessons(Module module, Module searchModule, String[] modu
...
+        char type;
+        Boolean isDone;
+        String param;
+        try {
+            type = getType(text);
+            isDone = isStatusDone(text);
+            param = getParam(text);
+        } catch (StringIndexOutOfBoundsException e) {
+            throw new InvalidSaveFile();
+        }
```
Comment (irving11119) [inline src/main/java/seedu/apollo/storage/Storage.java:327]: Good job on speedy bug fixes!

**Review by irving11119 — APPROVED** [review]
